# Generated by Django 4.0.5 on 2023-05-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_carusel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carusel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
