# Generated by Django 4.0.5 on 2023-05-22 18:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='carusel',
            name='body_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='carusel',
            name='body_uz',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='carusel',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carusel',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
